# Generated by Django 2.2.3 on 2019-07-27 05:44

from django.db import migrations, models
import django.db.models.deletion
import ziliao.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('name_full', models.CharField(blank=True, max_length=200, verbose_name='全名')),
                ('note_lable', models.CharField(max_length=200, verbose_name='备注')),
                ('_image', models.ImageField(upload_to=ziliao.models.category_image_path)),
                ('creat_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='ziliao.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标题')),
                ('note_lable', models.CharField(max_length=200, verbose_name='备注')),
                ('file_path', models.FileField(max_length=200, upload_to=ziliao.models.data_file_path)),
                ('creat_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ziliao.Category')),
            ],
        ),
    ]
