# Generated by Django 2.2.3 on 2019-07-27 11:49

from django.db import migrations, models
import ziliao.models


class Migration(migrations.Migration):

    dependencies = [
        ('ziliao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='_image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='ziliao/static/image/category/default.jpg', upload_to=ziliao.models.category_image_path, verbose_name='封面'),
        ),
    ]
