# Generated by Django 2.2.3 on 2019-07-28 03:56

from django.db import migrations, models
import django.utils.timezone
import ziliao.models


class Migration(migrations.Migration):

    dependencies = [
        ('ziliao', '0002_auto_20190727_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '资料类型', 'verbose_name_plural': '资料类型'},
        ),
        migrations.AlterModelOptions(
            name='datafile',
            options={'verbose_name': '资料文件', 'verbose_name_plural': '资料文件'},
        ),
        migrations.AlterField(
            model_name='category',
            name='creat_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='creat_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file_path',
            field=models.FileField(max_length=200, upload_to=ziliao.models.data_file_path, verbose_name='文件地址'),
        ),
    ]
