# Generated by Django 2.2.3 on 2019-07-27 11:49

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='head_image',
            field=models.ImageField(default='user/static/image/head/default.jpg', upload_to=user.models.head_image_path, verbose_name='头像'),
        ),
    ]
